import assert from 'node:assert/strict';
import {normalize,validateQuantity,matchingAlternatives,demoStock,searchProducts,safeUrl} from '../lib/catalog.ts';
const raw={id:1,name:'Автомат 160А',article:'SKU',price:100,url:'https://ekt.kz/catalog/item',description:'',quantity:10,stores:[{id:1,name:'Алматы',quantity:7},{id:2,name:'Брак',quantity:3}],properties:{NOMINALNYY_TOK:'250 А'}};
const p=normalize(raw);
assert.equal(p.conflict,true,'Conflicting rated current must be flagged');
assert.deepEqual(matchingAlternatives(p,[p]),[],'Conflicted product cannot be recommended');
assert.equal(demoStock(p),7,'Defective stock excluded from demo availability');
for(const n of [0,-1,1.5,NaN,Infinity,'2',100001])assert.throws(()=>validateQuantity(n));
assert.equal(validateQuantity(2),2);
assert.equal(searchProducts([p],'SKU').length,1);
assert.equal(safeUrl('javascript:alert(1)'), '');
assert.equal(safeUrl('https://evil.example/'), '');
assert.equal(safeUrl('https://ekt.kz/catalog/item'),'https://ekt.kz/catalog/item');
const properties={NOMINALNYY_TOK:'160 А',KOLICHESTVO_POLYUSOV:'3',NOMINALNOE_NAPRYAZHENIE:'400 В',NOMINALNAYA_OTKLYUCHAYUSHCHAYA_SPOSOBNOST:'18 кА'};
const good=normalize({...raw,properties});
const compatible=normalize({...raw,id:2,properties:{...properties,NOMINALNYY_TOK:'160А'}});
const incompatible=normalize({...raw,id:3,name:'Автомат 250А',properties:{...properties,NOMINALNYY_TOK:'250 А'}});
assert.deepEqual(matchingAlternatives(good,[compatible,incompatible]).map(p=>p.id),['2']);
assert.deepEqual(matchingAlternatives(good,[normalize({...raw,id:4,properties:{}})]),[]);
console.log('PASS: conflicts, normalization, quantity validation, stock exclusion, exact search, safe URLs, candidate constraints');
assert.equal(searchProducts([normalize({...raw,name:'LED STARK'})],'лампочки').length,1);
