import assert from 'node:assert/strict';
import {normalize} from '../lib/catalog.ts';
import {buildSolutionPlan,searchSolutionCandidates,validateSolutionDraft,parseSolutionChoice} from '../lib/solutions.ts';
import {runAgent} from '../lib/agent.ts';
const p={...normalize({id:101,name:'Автомат 25А',article:'a',price:100,quantity:10,properties:{NOMINALNYY_TOK:'25 А'}}),checkedAt:new Date().toISOString()};
const q={...p,id:'102',price:250};
assert.deepEqual(searchSolutionCandidates([p,q],'101 или 102').map(p=>p.id),['101','102']);
const need={id:'breaker',label:'Замена автомата',query:'25А',quantity:2,constraints:[{key:'NOMINALNYY_TOK',value:'25A'}]};
const item={id:'101',requirementId:'breaker',reason:'Указанный клиентом номинальный ток',evidenceKeys:['NOMINALNYY_TOK']};
const draft={goal:'Замена по подтверждённым параметрам',requirements:[need],options:[{key:'budget',title:'Основной',summary:'Подбор',tradeoffs:[],items:[item]},{key:'extended',title:'Другой',summary:'Другой товар',tradeoffs:['Цена выше; качество этим не подтверждено'],items:[{...item,id:'102'}]}],report:{assessment:'Причина поломки неизвестна',assumptions:[],exclusions:['Монтаж'],nextSteps:['Выбрать комплект']}};
const plan=buildSolutionPlan(draft,new Map([[p.id,p],[q.id,q]]),1000);
assert.deepEqual(plan.options.map(o=>o.total),[200,500]);assert.equal(Date.parse(plan.expiresAt),901000);
assert.throws(()=>validateSolutionDraft({...draft,requirements:[need,{...need,id:'extra'}]}));
assert.throws(()=>buildSolutionPlan(draft,new Map([[p.id,{...p,price:0}],[q.id,q]])));
assert.throws(()=>buildSolutionPlan(draft,new Map([[p.id,{...p,quantity:1}],[q.id,q]])));
assert.throws(()=>buildSolutionPlan(draft,new Map([[p.id,{...p,conflict:true}],[q.id,q]])));
assert.throws(()=>buildSolutionPlan(draft,new Map([[p.id,{...p,attributes:[]}],[q.id,q]])));
assert.throws(()=>buildSolutionPlan({...draft,options:[draft.options[0],{...draft.options[1],items:[item]}]},new Map([[p.id,p],[q.id,q]])));
assert.throws(()=>buildSolutionPlan({...draft,options:[{...draft.options[0],items:[{...item,evidenceKeys:['TIP_USTANOVKI']}]}]},new Map([[p.id,p]])));
for(const t of ['Выбираю бюджетный','Беру первый вариант.','Добавь вариант 1 в корзину'])assert.equal(parseSolutionChoice(t),'budget');
for(const t of ['Выбираю расширенный','Беру более дорогой комплект','Добавьте второй вариант в корзину!'])assert.equal(parseSolutionChoice(t),'extended');
for(const t of ['да','1','второй','Не выбираю бюджетный','Если я выбираю бюджетный','Выбираю бюджетный, но не добавляй','Что значит выбираю бюджетный?'])assert.equal(parseSolutionChoice(t),null);
const call=(name,args)=>({type:'function_call',call_id:crypto.randomUUID(),name,arguments:JSON.stringify(args)});
let prepared=0;let outputs=[call('prepare_solution',draft),call('find_solution_products',{requirements:[need]}),call('prepare_solution',draft),call('finish',{outcome:'needs_input',text:'Выберите вариант',productIds:[],suggestions:[]})];
const result=await runAgent({key:'fake',model:'fake',history:[],context:null,services:{search:async()=>({items:[]}),detail:async()=>p,alternatives:async()=>({items:[]}),cart:async()=>({items:[]}),prepare:async()=>{throw Error('Not allowed')},findSolution:async()=>({requirements:[{...need,candidates:[p,q]}]}),prepareSolution:async d=>{prepared++;return buildSolutionPlan(d,new Map([[p.id,p],[q.id,q]]));}},transport:async()=>Response.json({status:'completed',output:[outputs.shift()]})});
assert.equal(result.steps[0].ok,false);assert.equal(prepared,1);assert.equal(result.solution.options.length,2);assert.equal(result.proposal,undefined);
console.log('PASS solutions: coverage, exact constraints, evidence, conflicts, stock, totals, distinct variants, explicit choice, negation, provenance and model tool flow');

const failed=await runAgent({key:'fake',model:'fake',history:[],context:null,services:{search:async()=>({items:[]}),detail:async()=>p,alternatives:async()=>({items:[]}),cart:async()=>({items:[]}),prepare:async()=>null},transport:(()=>{const responses=[call('prepare_solution',draft),call('finish',{outcome:'needs_input',text:'Fake success: pick a bundle',productIds:[],suggestions:[{label:'Выбрать бюджетный',text:'Выбираю бюджетный',kind:'reply'}]})];return async()=>Response.json({status:'completed',output:[responses.shift()]});})()});
assert.match(failed.text,/Не удалось/);assert.deepEqual(failed.suggestions,[]);assert.equal(failed.solution,undefined);
