'use client';
import {useEffect,useState} from 'react';
import {ArrowUpRight,RefreshCw,LoaderCircle,X,Scale} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {api} from '@/lib/http-client';
import type {Product} from '@/lib/catalog';
import {ProductImage,money,dataTime} from './product-ui';

export function ProductComparison({open,onOpenChange,products,onRemove,onProduct}:{open:boolean;onOpenChange:(open:boolean)=>void;products:Product[];onRemove:(id:string)=>void;onProduct:(p:Product)=>void}){
 const [items,setItems]=useState<Product[]>([]),[loading,setLoading]=useState(false),[failed,setFailed]=useState<string[]>([]),[different,setDifferent]=useState(false),[revision,setRevision]=useState(0);
 const ids=products.map(p=>p.id).join(',');
 useEffect(()=>{if(!open)return;let active=true;setItems(products);setFailed([]);setLoading(true);
  void Promise.allSettled(products.map(p=>api<Product>('products/'+p.id))).then(results=>{if(!active)return;setItems(results.map((r,i)=>r.status==='fulfilled'?r.value:products[i]));setFailed(results.flatMap((r,i)=>r.status==='rejected'?[products[i].id]:[]));setLoading(false);});
  return()=>{active=false;};
 // Selection identity triggers a new live check; incoming cached copies must not restart it.
 // eslint-disable-next-line react-hooks/exhaustive-deps
 },[open,ids,revision]);
 const rows=[{key:'price',label:'Цена',values:items.map(p=>p.price&&p.price>0?money(p.price):null)},{key:'stock',label:'Общий остаток API',values:items.map(p=>p.quantity===null?null:String(p.quantity))},...Array.from(new Map(items.flatMap(p=>p.attributes.map(a=>[a.key,a.label] as const)))).map(([key,label])=>({key,label,values:items.map(p=>p.attributes.find(a=>a.key===key)?.value||null)}))];
 const differs=(values:(string|null)[])=>new Set(values.filter(v=>v!==null).map(v=>v!.toLowerCase().replace(/\s/g,'').replaceAll(',','.'))).size>1;
 const visible=rows.filter(r=>!different||differs(r.values)||r.values.some(v=>v===null));
 return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="comparison-dialog"><div className="comparison-heading"><span className="section-eyebrow"><Scale size={16}/> ВЫБОР ПО ПАРАМЕТРАМ</span><DialogTitle>Сравнение товаров</DialogTitle><DialogDescription>Характеристики из ekt.kz. Отсутствующие значения не считаются совпадением.</DialogDescription></div><div className="comparison-toolbar"><label><Checkbox checked={different} onCheckedChange={v=>setDifferent(v===true)}/>Отличия и неизвестные значения</label><button className="text-button" disabled={loading||!items.length} onClick={()=>setRevision(n=>n+1)}>{loading?<LoaderCircle size={16} className="spin"/>:<RefreshCw size={16}/>}Обновить данные</button></div>{failed.length>0&&<p className="warning" role="alert">Часть карточек не обновилась. В соответствующих колонках показаны сохранённые данные.</p>}<div className="comparison-scroll" tabIndex={0} aria-label="Таблица сравнения, прокручивается по горизонтали"><table className="comparison-table" style={{minWidth:190+Math.max(2,items.length)*240}}><thead><tr><th scope="col">{items.length} из 4 товаров</th>{items.map(p=><th scope="col" key={p.id}><button className="comparison-remove icon-button" aria-label={'Убрать из сравнения '+p.name} onClick={()=>onRemove(p.id)}><X size={16}/></button><ProductImage product={p}/><span className="sku">{p.manufacturerSku||p.sku}</span><button className="comparison-name" onClick={()=>{onOpenChange(false);onProduct(p);}}>{p.name}</button><small className={failed.includes(p.id)?'comparison-stale':''}>{loading?'Обновляю…':failed.includes(p.id)?'Не обновлено · ':'Получено · '}{!loading&&dataTime(p.dataAsOf)}</small>{(p.conflict||p.stockConflict)&&<p className="comparison-caution">Есть расхождение в данных</p>}</th>)}</tr></thead><tbody>{visible.map(row=><tr key={row.key} className={differs(row.values)?'comparison-difference':''}><th scope="row">{row.label}{differs(row.values)&&<small>Отличается</small>}</th>{row.values.map((value,i)=><td key={items[i].id} className={value===null?'comparison-unknown':''}>{value??'Нет подтверждённых данных'}</td>)}</tr>)}</tbody></table>{items.length<2&&<p className="comparison-empty">Добавьте ещё товар из каталога для сравнения.</p>}{different&&visible.length===0&&<p className="comparison-empty">В доступных параметрах отличий не найдено. Это не подтверждает взаимозаменяемость.</p>}</div><div className="comparison-footer"><p>Совпадение параметров не гарантирует взаимозаменяемость. Наличие для отгрузки, валюту и единицы продажи подтверждает магазин.</p><a href="https://ekt.kz" target="_blank" rel="noreferrer">Открыть ekt.kz <ArrowUpRight size={15}/></a></div></DialogContent></Dialog>;
}
