// Run from the project root: node scripts/audit-api.mjs [--refresh]
// Credentials stay in the server environment or ignored .env file.
import fs from 'node:fs';
import {normalize} from '../lib/catalog.ts';
const local=fs.existsSync('.env')?Object.fromEntries(fs.readFileSync('.env','utf8').split(/\r?\n/).filter(s=>s.includes('=')).map(s=>{const i=s.indexOf('=');return [s.slice(0,i),s.slice(i+1).replace(/^["']|["']$/g,'')]})):{};
const user=process.env.EKT_API_USER||local.EKT_API_USER,password=process.env.EKT_API_PASSWORD||local.EKT_API_PASSWORD;
if(!user||!password)throw Error('Set EKT_API_USER and EKT_API_PASSWORD in the environment or .env');
async function get(path){const r=await fetch('https://ekt.kz/api/'+path,{headers:{Authorization:'Basic '+Buffer.from(user+':'+password).toString('base64')},redirect:'error',signal:AbortSignal.timeout(15000)});if(!r.ok)throw Error('HTTP '+r.status);return r.json();}
const seed=JSON.parse(fs.readFileSync('data/catalog.json','utf8')),startedAt=new Date().toISOString(),pages=[];
for(let page=1;page<=seed.pages;page++){const r=await get('products?page='+page);if(!Array.isArray(r.items)||Number(r.page)!==page)throw Error('Invalid page '+page);pages.push(r);}
const listing=pages.flatMap(p=>p.items),rows=[],details=new Map();let cursor=0;
await Promise.all(Array.from({length:4},async()=>{while(cursor<listing.length){const item=listing[cursor++];try{const raw=await get('products/detail?id='+item.id);if(String(raw.id)!==String(item.id))throw Error('ID mismatch');const p=normalize(raw);details.set(String(item.id),raw);const cached=seed.items.find(s=>s.id===item.id);rows.push({id:p.id,sku:p.sku,manufacturerSku:p.manufacturerSku,name:p.name,price:p.price,quantity:p.quantity,priceMatchesList:p.price===normalize(item).price,cachedPriceChanged:cached?normalize(cached).price!==p.price:null,stockConflict:p.stockConflict,conflict:p.conflict,conflictText:p.conflictText,missingPrice:p.price===null,zeroPrice:p.price===0,missingQuantity:p.quantity===null,currencyProvided:('currency' in raw),checkedAt:new Date().toISOString()});}catch(e){rows.push({id:String(item.id),error:e.message});}}}));
const report={startedAt,finishedAt:new Date().toISOString(),scope:'Only the loaded sample, not the complete EKT catalog. API consistency is checked; physical stock and manufacturer specifications are not independently certified.',pages:pages.length,count:rows.length,succeeded:details.size,errors:rows.filter(r=>r.error),priceMismatches:rows.filter(r=>r.priceMatchesList===false),stockMismatches:rows.filter(r=>r.stockConflict),technicalConflicts:rows.filter(r=>r.conflict),missingPrices:rows.filter(r=>r.missingPrice),zeroPrices:rows.filter(r=>r.zeroPrice),missingQuantities:rows.filter(r=>r.missingQuantity),rows:rows.sort((a,b)=>Number(a.id)-Number(b.id))};
fs.writeFileSync('docs/api-audit.json',JSON.stringify(report,null,2)+'\n');
if(process.argv.includes('--refresh')){if(report.errors.length)throw Error('Audit has errors; seed left unchanged');fs.writeFileSync('data/catalog.json',JSON.stringify({...seed,syncedAt:startedAt,items:listing.map(p=>details.get(String(p.id)))},null,2)+'\n');}
if(process.argv.includes('--refresh'))fs.writeFileSync('data/catalog-preview.json',JSON.stringify({syncedAt:startedAt,items:listing.slice(0,12).map(p=>details.get(String(p.id)))})+'\n');
console.log(JSON.stringify({count:report.count,succeeded:report.succeeded,errors:report.errors.length,priceMismatches:report.priceMismatches.length,stockMismatches:report.stockMismatches.length,technicalConflicts:report.technicalConflicts.map(p=>({id:p.id,sku:p.manufacturerSku,conflict:p.conflictText})),missingPrices:report.missingPrices.length,zeroPrices:report.zeroPrices.length,missingQuantities:report.missingQuantities.length}));
